In [1]:
import cv2
import numpy as np
import os
import glob

# Defining the dimensions of checkerboard
CHECKERBOARD = (6,9) # inner corners. Ex: 7 by 10 squares = (6,9)
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)

In [2]:
import os
print(os.getcwd())

C:\Users\cbamm\1 Jupyter\Senior Design\Checkerboard Calibration


In [4]:
# Creating vector to store vectors of 3D points for each checkerboard image
objpoints = []
# Creating vector to store vectors of 2D points for each checkerboard image
imgpoints = [] 

output_dir = './annotated_images'
os.makedirs(output_dir, exist_ok=True)

# Defining the world coordinates for 3D points
objp = np.zeros((1, CHECKERBOARD[0]*CHECKERBOARD[1], 3), np.float32)
objp[0,:,:2] = np.mgrid[0:CHECKERBOARD[0], 0:CHECKERBOARD[1]].T.reshape(-1, 2)
prev_img_shape = None

In [5]:
images = glob.glob('./images/*.jpg') # checkerboard images file path

# NEEDED LATER - ADD SQUARE SIZES
#square_size = 25  # mm or whatever you printed
#objp[0,:,:2] = np.mgrid[0:CHECKERBOARD[0], 0:CHECKERBOARD[1]].T.reshape(-1,2)
#objp *= square_size


for fname in images:
    img = cv2.imread(fname)
    if img is None:
        print(f"Failed to load {fname}")
        continue

    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    ret, corners = cv2.findChessboardCornersSB(
        gray, CHECKERBOARD,
        cv2.CALIB_CB_ADAPTIVE_THRESH +
        cv2.CALIB_CB_FAST_CHECK +
        cv2.CALIB_CB_NORMALIZE_IMAGE
    )

    if ret:
        objpoints.append(objp)
        corners2 = cv2.cornerSubPix(gray, corners, (11,11), (-1,-1), criteria)
        imgpoints.append(corners2)

        img = cv2.drawChessboardCorners(img, CHECKERBOARD, corners2, ret)

        # Save annotated image
        basename = os.path.basename(fname)
        save_path = os.path.join(output_dir, f"annotated_{basename}")
        cv2.imwrite(save_path, img)
        print(f"Saved: {save_path}")


Saved: ./annotated_images\annotated_image_10.jpg
Saved: ./annotated_images\annotated_image_11.jpg
Saved: ./annotated_images\annotated_image_12.jpg
Saved: ./annotated_images\annotated_image_14.jpg
Saved: ./annotated_images\annotated_image_15.jpg
Saved: ./annotated_images\annotated_image_18.jpg
Saved: ./annotated_images\annotated_image_19.jpg
Saved: ./annotated_images\annotated_image_2.jpg
Saved: ./annotated_images\annotated_image_20.jpg
Saved: ./annotated_images\annotated_image_21.jpg
Saved: ./annotated_images\annotated_image_22.jpg
Saved: ./annotated_images\annotated_image_23.jpg
Saved: ./annotated_images\annotated_image_24.jpg
Saved: ./annotated_images\annotated_image_25.jpg
Saved: ./annotated_images\annotated_image_26.jpg
Saved: ./annotated_images\annotated_image_27.jpg
Saved: ./annotated_images\annotated_image_29.jpg
Saved: ./annotated_images\annotated_image_30.jpg
Saved: ./annotated_images\annotated_image_40.jpg
Saved: ./annotated_images\annotated_image_41.jpg
Saved: ./annotated_im

In [6]:
cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
h,w = img.shape[:2]
h, w

(480, 640)

In [8]:
"""
Performing camera calibration by 
passing the value of known 3D points (objpoints)
and corresponding pixel coordinates of the 
detected corners (imgpoints)
"""
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1],None,None)

In [9]:
print("mtx : \n")
print(mtx) # camera matrix

print("dist : \n")
print(dist) # [[k1, k2, p1, p2, k3]] distortion coefficients

print("rvecs : \n")
print(rvecs) # 

print("tvecs : \n")
print(tvecs) # 

mtx : 

[[503.5117531    0.         313.41348585]
 [  0.         503.14608551 243.09096517]
 [  0.           0.           1.        ]]
dist : 

[[ 2.11012608e-01 -4.84219584e-01  3.54574760e-04 -2.22622779e-03
   2.58098755e-01]]
rvecs : 

(array([[-0.15162779],
       [-0.30869468],
       [-1.53672158]]), array([[-0.60754413],
       [ 0.32459856],
       [-1.63538186]]), array([[-0.57862794],
       [ 0.34496113],
       [-1.64402711]]), array([[-0.52527257],
       [ 0.77532538],
       [-1.40944336]]), array([[-0.71051252],
       [ 0.44323147],
       [-1.6393774 ]]), array([[ 0.74664943],
       [-0.42094902],
       [-1.61129629]]), array([[ 0.7944631 ],
       [-0.43249528],
       [-1.61766102]]), array([[ 0.04613847],
       [-0.23585146],
       [-1.6059896 ]]), array([[ 0.47217713],
       [ 0.11278089],
       [-1.60497577]]), array([[-0.19774359],
       [ 0.85126077],
       [-1.49827366]]), array([[-0.82102944],
       [ 0.44875436],
       [-1.66686021]]), array([[-0.

In [14]:
print("tvecs[2]: \n")
print(tvecs[2]) # 

tvecs[2]: 

[[-3.46687647]
 [ 3.47464742]
 [12.88027647]]
