In [1]:
import cv2
import numpy as np
import os
import glob

# Defining the dimensions of checkerboard
CHECKERBOARD = (6,9) # inner corners. Ex: 7 by 10 squares = (6,9)
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)

In [2]:
import os
print(os.getcwd())

C:\Users\cbamm\1 Jupyter\Senior Design\Checkerboard Calibration


In [3]:
# Creating vector to store vectors of 3D points for each checkerboard image
objpoints = []
# Creating vector to store vectors of 2D points for each checkerboard image
imgpoints = [] 

output_dir = './annotated_images'
os.makedirs(output_dir, exist_ok=True)

# Defining the world coordinates for 3D points
objp = np.zeros((1, CHECKERBOARD[0]*CHECKERBOARD[1], 3), np.float32)
objp[0,:,:2] = np.mgrid[0:CHECKERBOARD[0], 0:CHECKERBOARD[1]].T.reshape(-1, 2)
prev_img_shape = None

In [4]:
images = glob.glob('./images/*.jpg') # checkerboard images file path

# NEEDED LATER - ADD SQUARE SIZES
#square_size = 25  # mm or whatever you printed
#objp[0,:,:2] = np.mgrid[0:CHECKERBOARD[0], 0:CHECKERBOARD[1]].T.reshape(-1,2)
#objp *= square_size


for fname in images:
    img = cv2.imread(fname)
    if img is None:
        print(f"Failed to load {fname}")
        continue

    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    ret, corners = cv2.findChessboardCorners(
        gray, CHECKERBOARD,
        cv2.CALIB_CB_ADAPTIVE_THRESH +
        cv2.CALIB_CB_FAST_CHECK +
        cv2.CALIB_CB_NORMALIZE_IMAGE
    )

    if ret:
        objpoints.append(objp)
        corners2 = cv2.cornerSubPix(gray, corners, (11,11), (-1,-1), criteria)
        imgpoints.append(corners2)

        img = cv2.drawChessboardCorners(img, CHECKERBOARD, corners2, ret)

        # Save annotated image
        basename = os.path.basename(fname)
        save_path = os.path.join(output_dir, f"annotated_{basename}")
        cv2.imwrite(save_path, img)
        print(f"Saved: {save_path}")


Saved: ./annotated_images\annotated_image_10.jpg
Saved: ./annotated_images\annotated_image_11.jpg
Saved: ./annotated_images\annotated_image_12.jpg
Saved: ./annotated_images\annotated_image_14.jpg
Saved: ./annotated_images\annotated_image_15.jpg
Saved: ./annotated_images\annotated_image_18.jpg
Saved: ./annotated_images\annotated_image_19.jpg
Saved: ./annotated_images\annotated_image_2.jpg
Saved: ./annotated_images\annotated_image_20.jpg
Saved: ./annotated_images\annotated_image_21.jpg
Saved: ./annotated_images\annotated_image_22.jpg
Saved: ./annotated_images\annotated_image_23.jpg
Saved: ./annotated_images\annotated_image_24.jpg
Saved: ./annotated_images\annotated_image_25.jpg
Saved: ./annotated_images\annotated_image_26.jpg
Saved: ./annotated_images\annotated_image_27.jpg
Saved: ./annotated_images\annotated_image_29.jpg
Saved: ./annotated_images\annotated_image_30.jpg
Saved: ./annotated_images\annotated_image_40.jpg
Saved: ./annotated_images\annotated_image_41.jpg
Saved: ./annotated_im

In [5]:
cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [6]:
h,w = img.shape[:2]
h, w

(480, 640)

In [7]:
"""
Performing camera calibration by 
passing the value of known 3D points (objpoints)
and corresponding pixel coordinates of the 
detected corners (imgpoints)
"""
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1],None,None)

In [8]:
print("mtx : \n")
print(mtx) # camera matrix

print("dist : \n")
print(dist) # [[k1, k2, p1, p2, k3]] distortion coefficients

print("rvecs : \n")
print(rvecs) # 

print("tvecs : \n")
print(tvecs) # 

mtx : 

[[503.51179012   0.         313.41350141]
 [  0.         503.14610486 243.09110798]
 [  0.           0.           1.        ]]
dist : 

[[ 2.11014320e-01 -4.84232133e-01  3.54626679e-04 -2.22615795e-03
   2.58120491e-01]]
rvecs : 

(array([[-0.31041628],
       [ 0.15247297],
       [ 1.57728648]]), array([[0.31415841],
       [0.58800252],
       [1.39889932]]), array([[0.33329976],
       [0.5590667 ],
       [1.39514277]]), array([[0.78762605],
       [0.53360605],
       [1.52205756]]), array([[0.4254074 ],
       [0.68193992],
       [1.34416152]]), array([[-0.40668304],
       [-0.72134573],
       [ 1.36352341]]), array([[-0.41599373],
       [-0.76415117],
       [ 1.33867999]]), array([[-0.23316866],
       [-0.04561397],
       [ 1.52237783]]), array([[ 0.11090232],
       [-0.4643115 ],
       [ 1.48273913]]), array([[0.84727736],
       [0.19681797],
       [1.46459403]]), array([[0.42510978],
       [0.77776716],
       [1.27922523]]), array([[0.28304691],
       [

In [9]:
import shutil
shutil.make_archive('annotated_images_backup', 'zip', './annotated_images')

'C:\\Users\\cbamm\\1 Jupyter\\Senior Design\\Checkerboard Calibration\\annotated_images_backup.zip'